- source_id: "source_gg"
  name: "google"
  url: "https://google.com"
- source_id: "source_yh"
  name: "yahoo"
  url: "https://yahoo.com"
- source_id: "source_bing"
  name: "bing"
  url: "https://bing.com"